name: Jalankan Jarvis
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Ambil Kode dari Repo
        uses: actions/checkout@v2

      - name: Persiapkan Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Bahan Tempur
        run: |
          python -m pip install --upgrade pip
          pip install pytelegrambotapi google-generativeai metaapi-cloud-sdk asyncio

      - name: Jalankan Mesin Jarvis
        run: python bot.py
